study("TD Sequential",overlay=true)
transp=input(0)
Numbers=input(true)
SR=input(true)
Barcolor=input(true)
TD = close > close[4] ?nz(TD[1])+1:0
TS = close < close[4] ?nz(TS[1])+1:0

TDUp = TD - valuewhen(TD < TD[1], TD , 1 )
TDDn = TS - valuewhen(TS < TS[1], TS , 1 )

plotshape(Numbers?(TDUp==8?true:na):na,style=shape.triangledown,text="8",color=white,location=location.abovebar,transp=transp)
plotshape(Numbers?(TDUp==9?true:na):na,style=shape.triangledown,text="9",color=white,location=location.abovebar,transp=transp)

plotshape(Numbers?(TDDn==8?true:na):na,style=shape.triangleup,text="8",color=white,location=location.belowbar,transp=transp)
plotshape(Numbers?(TDDn==9?true:na):na,style=shape.triangleup,text="9",color=white,location=location.belowbar,transp=transp)


// S/R Code By johan.gradin
//------------//
// Sell Setup //
//------------//
priceflip = barssince(close<close[4])
sellsetup = close>close[4] and priceflip
sell = sellsetup and barssince(priceflip!=9)
sellovershoot = sellsetup and barssince(priceflip!=10) or sellsetup and barssince(priceflip!=11)
sellovershoot1 = sellsetup and barssince(priceflip!=12) or sellsetup and barssince(priceflip!=13)
sellovershoot2 = sellsetup and barssince(priceflip!=14) or sellsetup and barssince(priceflip!=15)
sellovershoot3 = sellsetup and barssince(priceflip!=16) or sellsetup and barssince(priceflip!=17)

//----------//
// Buy setup//
//----------//
priceflip1 = barssince(close>close[4])
buysetup = close<close[4] and priceflip1
buy = buysetup and barssince(priceflip1!=9)
buyovershoot = barssince(priceflip1!=10) and buysetup or sellsetup and barssince(priceflip!=11)
buyovershoot1 = barssince(priceflip1!=12) and buysetup or sellsetup and barssince(priceflip!=13)
buyovershoot2 = barssince(priceflip1!=14) and buysetup or sellsetup and barssince(priceflip!=15)
buyovershoot3 = barssince(priceflip1!=16) and buysetup or sellsetup and barssince(priceflip!=17)

//----------//
// TD lines //
//----------//
TDbuyh = valuewhen(buy,high,0)
TDbuyl = valuewhen(buy,low,0)
TDsellh = valuewhen(sell,high,0)
TDselll = valuewhen(sell,low,0)

//----------//
//   Plots  //
//----------//

plot(SR?(TDbuyh ? TDbuyl: na):na,style=circles, linewidth=1, color=red)
plot(SR?(TDselll ? TDsellh : na):na,style=circles, linewidth=1, color=lime)
barcolor(Barcolor?(sell? #FF5252 : buy? #4CAF50		 : sellovershoot? #f5e072 : sellovershoot1? #f5e072 : sellovershoot2? #f5e072 : sellovershoot3? #f5e072 : buyovershoot? #f5e072 : buyovershoot1? #f5e072 : buyovershoot2? #f5e072 : buyovershoot3? #f5e072 : na):na)

